#!/bin/bash
APP=askbot
APP2=askbot_inst
APP3=`echo -n ask;echo bot`
set -e

# Retrieve arguments
domain=$1
path=$2
user=$3

# Check user parameter
sudo yunohost user list --json | grep -qi "\"username\": \"$user\"" \
	|| (echo "User does not exist: $user" && exit 1)
sudo yunohost app setting $APP admin_user -v $user

# Check domain/path availability
sudo yunohost app checkurl $domain$path -a $APP \
	|| (echo "Path not available: $domain$path" && exit 1)

# Remove trailing "/" for next commands
path=${path%/}

# Install dependencies
sudo apt-get update -qq
sudo apt-get install libmysqlclient-dev libpcre3 libpcre3-dev uwsgi supervisor -y -qq

# Generate random password
db_pwd=$(dd if=/dev/urandom bs=1 count=200 2> /dev/null | tr -c -d 'A-Za-z0-9' | sed -n 's/\(.\{24\}\).*/\1/p')

# Use 'owncloud' as database name and user
db_user=$APP

# Initialize database and store mysql password for upgrade
sudo yunohost app initdb $db_user -p $db_pwd
sudo yunohost app setting $APP mysqlpwd -v $db_pwd

# Delete db and user if exit with an error
function exit_properly
{
    set +e
    root_pwd=$(sudo cat /etc/yunohost/mysql)
    mysql -u root -p$root_pwd -e "DROP DATABASE $APP ; DROP USER $APP@localhost ;"

    sudo userdel $APP
    sudo rm -Rf /var/www/$APP2
    sudo rm -Rf /opt/$APP
    sudo rm -f /etc/nginx/conf.d/$domain.d/$APP.conf
    sudo rm -f /etc/supervisor/conf.d/$APP.conf
    exit 1
}
trap exit_properly ERR

# Create owncloud user
sudo useradd -d /var/www/$APP2 $APP \
	|| exit_properly
    
old_pwd=$(pwd)
# Copy files to the right place
sudo mkdir -p /opt/$APP
cd /opt/$APP
sudo pip install virtualenv
sudo virtualenv /opt/$APP
#sudo /bin/bash -c "source /opt/$APP/bin/activate"
sudo /opt/$APP/bin/pip install --upgrade setuptools
sudo /opt/$APP/bin/pip install $APP3
sudo /opt/$APP/bin/pip install uwsgi
sudo /opt/$APP/bin/pip install mysql-python
sudo /opt/$APP/bin/pip install --upgrade funcsigs
sudo /opt/$APP/bin/pip install --upgrade six
sudo /opt/$APP/bin/pip install django-robots==1.0

final_path=/var/www/$APP2
sudo mkdir -p $final_path

cd $final_path
cd ..
sudo /opt/askbot/local/lib/python2.7/site-packages/$APP3-setup -n $APP2 -e3 -d $db_user -u $db_user -p $db_pwd 
cd $APP2
#askbot-setup -n mydjangosite -e3 -d askbot -u askbot -p MXFYvsVwCOaiBZLvWhPFcCox
sudo python manage.py collectstatic --noinput
sudo chown -R $APP:www-data $final_path
sudo chmod -R g+w $final_path/askbo*/upfiles
sudo chmod -R g+w $final_path/log
sudo python manage.py syncdb --noinput
#sudo python manage.py migrate
cd $old_pwd
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$APP.conf
sudo cp ../conf/supervisord.conf /etc/supervisor/conf.d/$APP.conf
# Change variables in Owncloud configuration
if [[ "$path" == "" ]]; then
    sudo sed -i "s@LOCATIONTOCHANGE@/@g" /etc/nginx/conf.d/$domain.d/$APP.conf
else
	sudo sed -i "s@LOCATIONTOCHANGE@$path@g" /etc/nginx/conf.d/$domain.d/$APP.conf
    sudo sed -i "s@ASKBOT_URL = ''@ASKBOT_URL = '${path#'/'}/'@g" ${final_path}/settings.py
    sudo sed -i "s@STATIC_URL = '/m/'@STATIC_URL = '${path}/m/'@g" ${final_path}/settings.py
    sudo sed -i "s@MEDIA_URL = '/upfiles/'@MEDIA_URL = '${path}/upfiles/'@g" ${final_path}/settings.py
fi
sudo sed -i "s@PATHTOCHANGE@$path@g" /etc/nginx/conf.d/$domain.d/$APP.conf
sudo sed -i "s@ALIASTOCHANGE@$final_path/@g" /etc/nginx/conf.d/$domain.d/$APP.conf
sudo sed -i "s@NAMETOCHANGE@$APP@g" /etc/nginx/conf.d/$domain.d/$APP.conf
sudo sed -i "s@PATHVIRTUALENV@/opt/$APP@g" /etc/nginx/conf.d/$domain.d/$APP.conf
sudo sed -i "s@PATHVIRTUALENV@/opt/$APP@g" /etc/supervisor/conf.d/$APP.conf
sudo sed -i "s@NAMETOCHANGE@$APP@g" /etc/supervisor/conf.d/$APP.conf

# Reload Nginx and regenerate SSOwat conf
sudo service nginx reload
sudo yunohost app setting $APP unprotected_uris -v "/"
sudo yunohost app ssowatconf
sudo yunohost service add supervisor
sudo service supervisor restart
