#!/bin/bash

APP=askbot
set -e

# Retrieve arguments
domain=$(sudo yunohost app setting $APP domain)
path=$(sudo yunohost app setting $APP path)
#user=$(sudo yunohost app setting $APP admin_user)
db_pwd=$(sudo yunohost app setting $APP mysqlpwd)

# Install dependencies
sudo apt-get update -qq
sudo apt-get install libmysqlclient-dev -y -qq

# Remove trailing "/" for next commands
path=${path%/}

# Use 'owncloud' as database name and user \
db_user=$APP
